sudo: required
dist: trusty
language: c
addons:
  apt:
    packages:
      - libxinerama-dev
notifications:
  email:
    - tj+travis_uh_layout@a13.fr

env:
  - RUBYVER=2.4-stable
  - RUBYVER=2.3-stable
  - RUBYVER=2.2-stable
cache:
  directories:
    - ${HOME}/.gem/travis
    - ${HOME}/usr

before_install:
  - . <(curl -ksS https://vault.a13.fr/dev/travis-utils/install-before.sh)
install:
  - sed -i /development_dependency.\*uh-wm/d uh-layout.gemspec
  - . <(curl -ksS https://vault.a13.fr/dev/travis-utils/install.sh)
  - gem install uh-wm
script:
  - env -i sh <(curl -ksS https://vault.a13.fr/dev/travis-utils/build.sh)
