sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.1
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm:
      - ruby-head
      - rbx-2
notifications:
  email:
    - tj+travis_uh_layout@a13.fr
